apiVersion: apps/v1
kind: Deployment
metadata:
  name: phplabapp
  labels:
    app: phplabapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phplabapp
  template:
    metadata:
      labels:
        app: phplabapp
    spec:
      containers:
      - name: phplabapp
        image: rahulpoojar/phplab:v1
        ports:
        - containerPort: 80
